#ifndef DISTANCE_FUNCS_H
#define DISTANCE_FUNCS_H

#define F_L2_DISTANCE 1
#define F_FLOATVECTOR_L2_SQUARED_DISTANCE 2
#define F_HALFVECTOR_L2_DISTANCE 3
#define F_HALFVECTOR_L2_SQUARED_DISTANCE 4
#define F_INT8VECTOR_L2_DISTANCE 5
#define F_INT8VECTOR_L2_SQUARED_DISTANCE 6
#define F_COSINE_DISTANCE 7
#define F_HALFVECTOR_COSINE_DISTANCE 8
#define F_INNER_PRODUCT 9
#define F_FLOATVECTOR_NEGATIVE_INNER_PRODUCT 10
#define F_HALFVECTOR_INNER_PRODUCT 11
#define F_HALFVECTOR_NEGATIVE_INNER_PRODUCT 12
#define F_INT8VECTOR_INNER_PRODUCT 13
#define F_INT8VECTOR_NEGATIVE_INNER_PRODUCT 14
#define F_FLOATVECTOR_SPHERICAL_DISTANCE 15
#define F_HALFVECTOR_SPHERICAL_DISTANCE 16
#define F_INT8VECTOR_SPHERICAL_DISTANCE 17
#define F_INT8VECTOR_COSINE_DISTANCE 18

#endif
