/**
 * Copyright ...
 */

#ifndef ANNVECTOR_ARCHITECTURE_MACRO_H
#define ANNVECTOR_ARCHITECTURE_MACRO_H

/* compilers */
#if defined(__clang__)
#define ANN_COMPILER_CLANG 1
#else
#define ANN_COMPILER_CLANG 0
#endif

#if defined(__GNUC__) && !defined(__clang__)
#define ANN_COMPILER_GCC 1
#else
#define ANN_COMPILER_GCC 0
#endif

#if ANN_COMPILER_GCC
#define ANN_GCC_VERSION (__GNUC__ * 100 + __GNUC_MINOR__)
#define ANN_GCC_VERSION_GE(a, b) (ANN_GCC_VERSION >= (a * 100 + b))
#else
#define ANN_GCC_VERSION 0
#define ANN_GCC_VERSION_GE(a, b) 0
#endif

#if ANN_COMPILER_CLANG
#define ANN_CLANG_VERSION (__clang_major__ * 100 + __clang_minor__)
#define ANN_CLANG_VERSION_GE(a, b) (ANN_CLANG_VERSION >= (a * 100 + b))
#else
#define ANN_CLANG_VERSION 0
#define ANN_CLANG_VERSION_GE(a, b) 0
#endif

/* archs */
#if defined(__x86_64__)
#define COMPILER_TARGET_X86_64 1
#else
#define COMPILER_TARGET_X86_64 0
#endif

#if defined(__arm__) || defined(__arm) || defined(__aarch64__) || defined(__aarch64)
#define COMPILER_TARGET_ARM 1
#else
#define COMPILER_TARGET_ARM 0
#endif

#if defined(__aarch64__) || defined(__aarch64) || defined(_M_ARM64)
#define COMPILER_TARGET_AARCH64 1
#else
#define COMPILER_TARGET_AARCH64 0
#endif

/* x86 inst */
#if COMPILER_TARGET_X86_64 && (ANN_GCC_VERSION_GE(4, 3) || ANN_CLANG_VERSION_GE(3, 2))
#define COMPILER_SUPPORT_SSE 1
#else
#define COMPILER_SUPPORT_SSE 0
#endif

#if COMPILER_TARGET_X86_64 && (ANN_GCC_VERSION_GE(4, 7) || ANN_CLANG_VERSION_GE(3, 5))
#define COMPILER_SUPPORT_AVX 1
#else
#define COMPILER_SUPPORT_AVX 0
#endif

#if COMPILER_TARGET_X86_64 && (ANN_GCC_VERSION_GE(4, 9) || ANN_CLANG_VERSION_GE(3, 9))
#define COMPILER_SUPPORT_AVX512 1
#else
#define COMPILER_SUPPORT_AVX512 0
#endif

#if COMPILER_TARGET_X86_64 && (ANN_GCC_VERSION_GE(6, 1) || ANN_CLANG_VERSION_GE(6, 0))
#define COMPILER_SUPPORT_AVX512_DQ 1
#else
#define COMPILER_SUPPORT_AVX512_DQ 0
#endif

#if COMPILER_TARGET_X86_64 && (ANN_GCC_VERSION_GE(6, 1) || ANN_CLANG_VERSION_GE(6, 0))
#define COMPILER_SUPPORT_AVX512_BW 1
#else
#define COMPILER_SUPPORT_AVX512_BW 0
#endif

#if COMPILER_TARGET_X86_64 && (ANN_GCC_VERSION_GE(6, 1) || ANN_CLANG_VERSION_GE(6, 0))
#define COMPILER_SUPPORT_AVX512_VL 1
#else
#define COMPILER_SUPPORT_AVX512_VL 0
#endif

#define COMPILER_SUPPORT_AVX512_EXTEND \
    (COMPILER_SUPPORT_AVX512_DQ && COMPILER_SUPPORT_AVX512_BW && COMPILER_SUPPORT_AVX512_VL)

/* arm inst */
#if COMPILER_TARGET_ARM && (ANN_GCC_VERSION_GE(4, 6) || ANN_CLANG_VERSION_GE(3, 2))
#define COMPILER_SUPPORT_NEON 1
#else
#define COMPILER_SUPPORT_NEON 0
#endif

#if COMPILER_TARGET_ARM && (ANN_GCC_VERSION_GE(8, 1) || ANN_CLANG_VERSION_GE(5, 0))
#define COMPILER_SUPPORT_SVE 1
#else
#define COMPILER_SUPPORT_SVE 0
#endif

#if COMPILER_TARGET_ARM && (ANN_GCC_VERSION_GE(10, 1) || ANN_CLANG_VERSION_GE(9, 0))
#define COMPILER_SUPPORT_SVE2 1
#else
#define COMPILER_SUPPORT_SVE2 0
#endif

#if COMPILER_TARGET_ARM && (ANN_GCC_VERSION_GE(14, 0) || ANN_CLANG_VERSION_GE(18, 0))
#define COMPILER_SUPPORT_SME 1
#else
#define COMPILER_SUPPORT_SME 0
#endif

#if COMPILER_TARGET_ARM && (ANN_GCC_VERSION_GE(14, 0) || ANN_CLANG_VERSION_GE(18, 0))
#define COMPILER_SUPPORT_SME2 1
#else
#define COMPILER_SUPPORT_SME2 0
#endif

#if COMPILER_TARGET_ARM && (ANN_GCC_VERSION_GE(8, 0) || ANN_CLANG_VERSION_GE(6, 8))
#define COMPILER_SUPPORT_DOTPROD 1
#else
#define COMPILER_SUPPORT_DOTPROD 0
#endif

#if COMPILER_TARGET_ARM && (ANN_GCC_VERSION_GE(12, 0) || ANN_CLANG_VERSION_GE(14, 0))
#define COMPILER_SUPPORT_ARMV9 1
#else
#define COMPILER_SUPPORT_ARMV9 0
#endif

#define COMPILER_SUPPORT_NEONV8 COMPILER_SUPPORT_NEON
// #define COMPILER_SUPPORT_SVEV8 COMPILER_SUPPORT_SVE
// #define COMPILER_SUPPORT_SVE2V8 COMPILER_SUPPORT_SVE2
/* temporarily disable sve */
#define COMPILER_SUPPORT_SVEV8 0
#define COMPILER_SUPPORT_SVE2V8 0

#define COMPILER_SUPPORT_SMEV9 (COMPILER_SUPPORT_ARMV9 && COMPILER_SUPPORT_SME)
#define COMPILER_SUPPORT_SME2V9 (COMPILER_SUPPORT_ARMV9 && COMPILER_SUPPORT_SME2)

/* utils */
#if COMPILER_SUPPORT_SSE
#define DISTANCER_ISAS_SSE (SSE)
#else
#define DISTANCER_ISAS_SSE
#endif

#if COMPILER_SUPPORT_AVX
#define DISTANCER_ISAS_AVX (AVX)
#else
#define DISTANCER_ISAS_AVX
#endif

#if COMPILER_SUPPORT_AVX512_EXTEND
#define DISTANCER_ISAS_AVX512 (AVX512)
#else
#define DISTANCER_ISAS_AVX512
#endif

#if COMPILER_SUPPORT_NEONV8
#define DISTANCER_ISAS_NEONV8 (NEONV8)
#else
#define DISTANCER_ISAS_NEONV8
#endif

#if COMPILER_SUPPORT_SVEV8
#define DISTANCER_ISAS_SVEV8 (SVEV8)
#else
#define DISTANCER_ISAS_SVEV8
#endif

#if COMPILER_SUPPORT_SVE2V8
#define DISTANCER_ISAS_SVE2V8 (SVE2V8)
#else
#define DISTANCER_ISAS_SVE2V8
#endif

#if COMPILER_SUPPORT_SMEV9
#define DISTANCER_ISAS_SMEV9 (SMEV9)
#else
#define DISTANCER_ISAS_SMEV9
#endif

#if COMPILER_SUPPORT_SME2V9
#define DISTANCER_ISAS_SME2V9 (SME2V9)
#else
#define DISTANCER_ISAS_SME2V9
#endif

#define DISTANCER_ISAS_GENERAL (GENERAL)
#define DISTANCER_ISAS \
    DISTANCER_ISAS_SSE \
    DISTANCER_ISAS_AVX \
    DISTANCER_ISAS_AVX512 \
    DISTANCER_ISAS_NEONV8 \
    DISTANCER_ISAS_SVEV8 \
    DISTANCER_ISAS_SVE2V8 \
    DISTANCER_ISAS_SMEV9 \
    DISTANCER_ISAS_SME2V9 \
    DISTANCER_ISAS_GENERAL

#endif /* ANNVECTOR_ARCHITECTURE_MACRO_H */
